GRANT DROP ANY TABLE, ALTER ANY TABLE TO DBMAINT;
GRANT CREATE JOB TO DBMAINT;
GRANT MANAGE SCHEDULER TO DBMAINT;

exec DBMS_SERVICE.CREATE_SERVICE(service_name=>'DBMAINT_JOBS', network_name=>'DBMAINT_JOBS');
exec DBMS_SERVICE.START_SERVICE('DBMAINT_JOBS'); 

BEGIN
  DBMS_SCHEDULER.CREATE_JOB_CLASS(
    job_class_name => 'DBMAINT_JOBS_CLASS',
    service        => 'DBMAINT_JOBS',
    logging_level  => DBMS_SCHEDULER.LOGGING_RUNS
  );
END;
/
grant execute on sys.DBMAINT_JOBS_CLASS to DBMAINT;

-- one time
exec DBMS_SCHEDULER.SET_ATTRIBUTE(name => 'DBMAINT.TBS_MAINTENANCE_JOB', attribute => 'job_class', value  => 'DBMAINT_JOBS_CLASS');
