  CREATE TABLE "MLION"."APII_TRANS"
   (    "APII_TRANS_ID" NUMBER(18,0) NOT NULL ENABLE,
        "IN_TS" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE,
        "IN_TS_PROVIDER" DATE,
        "RSP_TS" DATE,
        "METHOD_ID" NUMBER(18,0) NOT NULL ENABLE,
        "IP_ADDR" VARCHAR2(15),
        "TRANS_ID" VARCHAR2(60),
        "TRANS_ID_PROVIDER" VARCHAR2(60),
        "PROVIDER_ID" NUMBER(18,0) NOT NULL ENABLE,
        "RSP_CODE" VARCHAR2(10),
        "CLIENT_ID" NUMBER(18,0),
        "EACCT" VARCHAR2(73),
        "API_NAME" VARCHAR2(20),
        "LOG_DATA" VARCHAR2(4000),
        "USER_AGENT" VARCHAR2(255),
        "TRANS_AMT" NUMBER(14,2),
        "REQ_TS" DATE DEFAULT SYSDATE,
        "PROC_TIME" NUMBER(10,5),
        "PROVIDER_TS" DATE,
        "APII_APP_ID" NUMBER(18,0),
        "XID" NUMBER(12,0),
        "PROD_ID" NUMBER(18,0),
        "RESULT_TRANS_ID" NUMBER(18,0),
        "RESULT_TRANS_TBL" VARCHAR2(30),
        "LOCATION" VARCHAR2(25),
        "LOCATION_TYPE" NUMBER(18,0),
        "SERVER" VARCHAR2(20),
        "AGENT" VARCHAR2(20),
        "AGENT_ID" VARCHAR2(255),
        "AGENT_FNAME" VARCHAR2(255),
        "AGENT_LNAME" VARCHAR2(255),
        "RTOKEN" VARCHAR2(36),
         CHECK ("APII_TRANS_ID" IS NOT NULL) ENABLE,
         CHECK ("IN_TS" IS NOT NULL) ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 20 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
  PARTITION BY RANGE ("APII_TRANS_ID") INTERVAL (1000000)
  SUBPARTITION BY HASH ("IN_TS")
  SUBPARTITIONS 10
 (PARTITION "SYS_P176923"  VALUES LESS THAN (12637000000)
PCTFREE 10 PCTUSED 40 INITRANS 20 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
 ( SUBPARTITION "SYS_SUBP176913" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP176914" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP176915" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP176916" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP176917" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP176918" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP176919" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP176920" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP176921" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP176922" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_DATA"
 NOCOMPRESS ) ) ;
  CREATE UNIQUE INDEX "MLION"."PK_APII_TRANS_REPART" ON "MLION"."APII_TRANS" ("APII_TRANS_ID", "IN_TS")
  PCTFREE 10 INITRANS 50 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX"  LOCAL
 (PARTITION "SYS_P176923" NOCOMPRESS
PCTFREE 10 INITRANS 50 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX"
 ( SUBPARTITION "SYS_SUBP176913"
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX" ,
  SUBPARTITION "SYS_SUBP176914"
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX" ,
  SUBPARTITION "SYS_SUBP176915"
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX" ,
  SUBPARTITION "SYS_SUBP176916"
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX" ,
  SUBPARTITION "SYS_SUBP176917"
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX" ,
  SUBPARTITION "SYS_SUBP176918"
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX" ,
  SUBPARTITION "SYS_SUBP176919"
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX" ,
  SUBPARTITION "SYS_SUBP176920"
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX" ,
  SUBPARTITION "SYS_SUBP176921"
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX" ,
  SUBPARTITION "SYS_SUBP176922"
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MLION_INDX" ) ) ;
ALTER TABLE "MLION"."APII_TRANS" ADD CONSTRAINT "PK_APII_TRANS_REPART" PRIMARY KEY ("APII_TRANS_ID", "IN_TS")
  USING INDEX "MLION"."PK_APII_TRANS_REPART"  ENABLE;
