  CREATE TABLE "SOFI"."APII_TRANS"
   (    "APII_TRANS_ID" NUMBER(12,0) NOT NULL ENABLE,
        "IN_TS" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE,
        "IN_TS_PROVIDER" DATE,
        "RSP_TS" DATE,
        "METHOD_ID" NUMBER(18,0) NOT NULL ENABLE,
        "IP_ADDR" VARCHAR2(15),
        "TRANS_ID" VARCHAR2(60),
        "TRANS_ID_PROVIDER" VARCHAR2(60),
        "PROVIDER_ID" NUMBER(18,0) NOT NULL ENABLE,
        "RSP_CODE" VARCHAR2(10),
        "CLIENT_ID" NUMBER(18,0),
        "EACCT" VARCHAR2(73),
        "API_NAME" VARCHAR2(20),
        "LOG_DATA" VARCHAR2(4000),
        "USER_AGENT" VARCHAR2(255),
        "TRANS_AMT" NUMBER(14,2),
        "REQ_TS" DATE DEFAULT SYSDATE,
        "PROC_TIME" NUMBER(10,5),
        "PROVIDER_TS" DATE,
        "APII_APP_ID" NUMBER(18,0),
        "XID" NUMBER(12,0),
        "PROD_ID" NUMBER(18,0),
        "RESULT_TRANS_ID" NUMBER(18,0),
        "RESULT_TRANS_TBL" VARCHAR2(30),
        "LOCATION" VARCHAR2(25),
        "LOCATION_TYPE" NUMBER(18,0),
        "SERVER" VARCHAR2(20),
        "AGENT" VARCHAR2(20),
        "AGENT_ID" VARCHAR2(255),
        "AGENT_FNAME" VARCHAR2(255),
        "AGENT_LNAME" VARCHAR2(255),
        "RTOKEN" VARCHAR2(36),
         CHECK ("APII_TRANS_ID" IS NOT NULL) ENABLE,
         CHECK ("IN_TS" IS NOT NULL) ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
  PARTITION BY RANGE ("IN_TS") INTERVAL (NUMTODSINTERVAL(7,'DAY'))
  SUBPARTITION BY HASH ("APII_TRANS_ID")
  SUBPARTITIONS 32
 (PARTITION "SYS_P49668"  VALUES LESS THAN (TIMESTAMP' 2026-04-26 00:00:00')
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 ( SUBPARTITION "SYS_SUBP49636" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49637" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49638" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49639" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49640" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49641" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49642" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49643" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49644" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49645" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49646" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49647" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49648" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49649" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49650" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49651" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49652" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49653" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49654" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49655" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49656" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49657" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49658" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49659" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49660" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49661" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49662" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49663" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49664" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49665" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49666" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP49667" SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_DATA"
 NOCOMPRESS ) ) ;
  CREATE UNIQUE INDEX "SOFI"."PK_APII_TRANSP" ON "SOFI"."APII_TRANS" ("APII_TRANS_ID") REVERSE
  PCTFREE 10 INITRANS 50 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SOFI_INDX"  GLOBAL PARTITION BY HASH ("APII_TRANS_ID")
 (PARTITION "SYS_P73" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P74" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P75" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P76" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P77" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P78" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P79" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P80" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P81" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P82" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P83" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P84" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P85" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P86" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P87" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P88" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P89" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P90" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P91" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P92" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P93" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P94" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P95" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P96" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P97" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P98" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P99" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P100" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P101" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P102" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P103" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ,
 PARTITION "SYS_P104" NOCOMPRESS
  TABLESPACE "SOFI_INDX" ) ;
ALTER TABLE "SOFI"."APII_TRANS" ADD CONSTRAINT "PK_APII_TRANSP" PRIMARY KEY ("APII_TRANS_ID")
  USING INDEX "SOFI"."PK_APII_TRANSP"  ENABLE;
